ONSdigital/sdc-global-design-patterns

components/02-form-elements/input/README.md
components/02-form-elements/input/input--percentage.hbs
components/02-form-elements/input/input.config.js

Percentage pattern is added as an input to form elements. 
to test:
- run 'Yarn Start' on this branch 
- percentage should be added to 'Form Elements' > 'Input'

Adding percentage patterns from survey runner into design library

---

gulpfile.babel.js

**What is the context of this PR?**
- Whenever a component is updated the yarn compile/start should happen automatically
Resolves: #16
**How to review**
Pull down branch and run yarn start.
Update a component file and check that gulp automatically runs the compile/build task.

Improving scss watch scope

---

components/02-form-elements/unit/unit.config.js

The units were displaying empty `label` elements and would not have tested correctly with DAC.
I have added `label_for` to link the label to the `input` and added `label_text` to provide a more descriptive label for each input.

Added label_text and label_for for each unit variant

---

components/answer/_answer.scss
components/date/_date.scss
components/feedback/_feedback.scss
components/form/_form.scss
components/guidance/_guidance.scss
components/lock/_lock.scss
components/question/_question.scss

The pattern library needed the addition of some `.scss` files that were not in the repository to bring it up to par with the eQ Runner styles. Until this has been completed and tested it will not be possible to use the CDN for eQ Runner.
__Files added:__
- `components/answer/_answer.scss`
- `components/date/_date.scss`
- `components/feedback/_feedback.scss`
- `components/form/_form.scss`
- `components/guidance/_guidance.scss`
- `components/lock/_lock.scss`
- `components/question/_question.scss`
Compare the component .scss files with those from eQ Runner and that they appear in the output .css file.

Adds component .scss files from eQ Runner not in SDC pattern library

---

package.json

Adds the `compile_assets` step to the build task so that it actually has compiled assets to copy to the dist folder.
Check it works:
https://deploy-preview-57--sdc-pattern-library.netlify.com/

Make Netlify Work

---

components/highlight/README.md
components/highlight/highlight.config.js

Updated highlight to use `<em>` so that it is semantically correct. Highlight applied to `<span>` or other non-emphasising elements should be regarded as incorrect as it would be providing different experiences to different users.
Review `readme.md` amendments for clarity.

Corrected highlight to use em and updated notes for usage

---

README.md
ci/concourse.yml

When a Github release is created on this repo, The release version will be deployed to the CDN under the release version
Eg. `https://cdn.ons.gov.uk/sdc/v1.0.0/img/icons/icons--accordion.svg`

Push release tags to the CDN

---

components/03-grid/_grid.scss

A bug in the logic for building the grid columns meant that the source order of the statements was based around the number of columns, rather than the width in the media query.
As a result, the CSS was in the wrong order, causing unexpected results.
This PR swaps the two inner and outer loops around so that the CSS is in the correct order to behave as expected.
1. **On MASTER** Add the following markup somewhere (eg. grid.hbs)
```
<div class="grid">
<div class="grid__col col-2@xs col-4@s col-6@m col-8@l col-12@xl">
<div class="grid__helper">column</div>
</div>
</div>
<div class="grid">
<div class="grid__col col-12@xs col-8@s col-6@m col-4@l col-2@xl">
<div class="grid__helper">column</div>
</div>
</div>
```
2. Observe that the second column doesn't behave as expected (it should shrink as …

Fix issue with grid breakpoint source order

---

components/summary/summary--errors.hbs

Now contains invalid data to justify error message.
Existing error message indicated that £300+£200+£100 did not equal £600.

Fix the example group validation summary.

---

components/02-form-elements/duration/duration.config.js
components/02-form-elements/duration/duration.hbs
components/02-form-elements/fields/field/_field.scss
components/02-form-elements/input-type/_input-type.scss
components/02-form-elements/input/_input.scss

Problem shown in screenshot below:
Solution - To maintain the input width i've created two duration types (and got rid of 3 that were not doing anything) which cater for time types (mins, secs, hours) and period types (days, months, years). 
Check that the solution works ok

Allow for longer strings in duration type input

---

ci/concourse.yml

The CI build was failing due to pulling the latest node docker image and then the node-sass version not being compatible.
This is a temporary measure and we aim to upgrade other dependencies to work with the newer node version.

Pins to node 8 for the CI build

---

ci/concourse.yml

Updates the pinned node version (#102) for the CI build to 10.2.1 (updated in #104)

Update node version used in CI build

---

ci/concourse.yml
ci/secrets.yml.example

Slack alerts are sent out when the build or deploy fails
http://concourse.dev.eq.ons.digital/teams/main/pipelines/sdc-global-design-patterns

Added slack alerts for build and deploy failures

---

gulpfile.babel.js

Bundled scripts were being left un-minified. 
Fix is to add a separate gulp task which:
- takes the completed bundled script (`public/assets/scripts/bundle.js`)
- produces a minified version using `uglify`,
- appends a `.min` suffix
- and places it in the `public/assets/scripts/` folder.
Pull this branch and run `yarn compile_assets` watch the `public/assets/scripts` folder and check that the minified file is produced.
Check cli for any errors.
#114

Added a separate gulp task to produce a minified bundle.js

---

components/_preview-skip.hbs
components/skip/_skip.scss
components/skip/skip.config.js
components/skip/skip.hbs

Explicitly defining link colour for the 'Skip to content' link as it is displayed on a dark background on business and Census surveys.
Use the Netlify preview link to view the 'Skip to content' component in the pattern library and test the skip to content link.
Resolves #118

Defining link colour for skip to content

---

assets/sass/partials/behaviours/_details-toggle.scss
components/definition/_definition.scss
components/details/_details.scss

Removed the `overflow:hidden` from the definition component as this was obscuring the 'Close this' button offset highlight.
Test the definitions component.
Resolves #120

overflow:hidden removed from definition component

---

components/skip/_skip.scss

Quick fix for the gap that is present between the skip to content link and the highlight.
Review the netlify build on different resolutions and devices.
Fixes #125

added box-shadow to bridge the highlight offset on skip to content link

---

components/_preview-skip.hbs

The 'skip to content' component preview file referenced a now re-named file.
Check that the skip to content component renders correctly.

Skip to content fix for preview file.

---

components/02-form-elements/input/_input.scss

Define the max-width of the `textarea` element to avoid it resizing beyond the container.
Review the code in the .scss and the implementation in the textarea component on netlify.
Resolves #159

Addition of max-width property to avoid out of bounds resizing.

---

components/02-form-elements/textarea/character-limit.js

Using lodash for forEach node iteration to fix issues caused by its use in IE11 and iOS9 Safari where the textarea module was breaking and causing other components to fail (input password and mobile nav).
Review the affected components on this PR's Netlify instance.
resolves #157 , #156

Character limit fix - Using lodash for forEach node iteration

---

assets/sass/partials/utilities/_utilities.scss

There is a need to disable the wrapping of financial or other unit based values to make them more legible/comprehensible.
Add the `u-nowrap` to a highlight and edit the copy to attempt to force a word-wrap.
Resolves #160

Added a .u-nowrap utility class

---

components/definition/_definition.scss
components/guidance/_guidance.scss

With js disabled, the guidance content was hidden and should be shown.
Check the guidance component displays the content when js is disabled.

Add has-js class to guidance content to fix bug

---

components/02-form-elements/mutually-exclusive/mutually-exclusive--date.hbs
components/02-form-elements/mutually-exclusive/mutually-exclusive.config.js
components/02-form-elements/mutually-exclusive/mutually-exclusive.hbs
components/02-form-elements/mutually-exclusive/mutually-exclusive.js
tests/karma/spec/mutuallyexclusive.spec.js

Existing mutually exclusive functionality is scoped to `checkbox` input type.
Extended to work with `text` and `select` types.
Another example has been added to the pattern library under "Mutually exclusive" which demonstrates the mutually exclusive working with a date input which includes `text` and `select` input types.
Check that it works as expected and that the existing `checkbox` scenario works as expected.

Extended mutually exclusive js to work with all field types

---

components/collapsible/_collapsible.scss

Small issue where the collapsible chevron was displayed on hover when javascript was disabled.
Turn off JS and check the feedback component.
The title should not display an icon on hover.

Added after selector to the no-js class

---

components/02-form-elements/duration/README.md
components/02-form-elements/duration/duration.hbs
components/02-form-elements/input-type/_input-type.scss
components/02-form-elements/unit/README.md

A bug found where the `input-type__type--` was breaking when used in certain scenarios.
There was no `readme` for the usage.
Check the `duration` input types and `unit` input types work correctly. 
Check the `readme` makes sense.

Fixed issue with unit inputs and updates readme

---

assets/sass/partials/vars/_forms.scss
components/02-form-elements/duration/README.md
components/02-form-elements/duration/duration.hbs
components/02-form-elements/input-type/_input-type.scss
components/02-form-elements/unit/README.md
components/02-form-elements/unit/unit.hbs

After testing in runner the existing way the unit types were handled required reworking.
All width limits have now been removed to allow for any string length.
Check the unit and duration input components render as they should across browsers and viewports.
Closes #77

Refactored the unit input type to allow any string length

---

components/02-form-elements/input-type/_input-type.scss

Found a bug to do with the changes made to the input types. The currency was positioned left and lacked a width constraint.
Check the currency type looks as it should.

Bug currency position

---

components/02-form-elements/input-type/_input-type.scss

Left padding required for the `currency` input type.
Check it's ok.

Fixed issue with padding on currency

---

assets/js/api/_load.js
assets/js/components.js
assets/js/polyfills.js

Remove double import of babel-polyfill and place in polyfills file.
Fixes #221

Move babel-polyfill to polyfills file to prevent duplicate error

---

components/timeout/timeout.dom.js

[trello](https://trello.com/c/ASwVT0ss/2577-expire-session-being-blocked-by-the-waf)
The WAF is blocking requests which don't include a 'Content-Type' header.
Since the expire-session POST request has an empty body, the fetch API does not set a content-type header, and the request is being blocked by the WAF.
Though it is debatable whether a POST request with an empty body should have a content-type, in this case it's much easier to change our request than to change the WAF rule. The content-type of a request with no body is not properly specified by the W3C standard.
As discussed with Shane, the functionality here potentially shouldn't be in the pattern library at all, though that is likely a wider discussion.

Set a content-type of application json on expire session

---

components/02-form-elements/date/date.hbs
components/02-form-elements/fields/field/_field.scss

Added in temporary fix for date input with dropdown to allow us to run with mobile font size improvements until runner has been updated to use number inputs for the month.

Added temporary fix for month dropdown date input on mobile

---

components/02-form-elements/mutually-exclusive/mutually-exclusive.js
tests/karma/spec/mutuallyexclusive.spec.js

Resolves https://github.com/ONSdigital/sdc-global-design-patterns/issues/236
When filling in a textarea / checking a checkbox option etc in a mutually exclusive component, it was clearing the value of the mutually exclusive checkbox meaning no value is sent to the server in runner, breaking functional tests.

Ensure exclusive checkbox value is not cleared

---

assets/sass/partials/base/_print.scss

Prevent text from being split across pages on iOS when printing
