ONSdigital/sdc-global-design-patterns

assets/sass/eq-patternlib/eq-patternlib.scss
#4 and #5 Resolved in this branch.
=> Fixes for issues #4 and #5

README.md, docs/08-feedback.md
=> Minor housekeeping tasks relating to the change of repo name.

assets/sass/partials/vars/_forms.scss
This allows units to be displayed correctly to match eq-survey-runner
=> Update _forms.scss for vars to match survey runner

components/highlight/README.md, components/highlight/highlight.config.js, components/highlight/highlight.hbs
Adding the documentation for the highlight component to the pattern library.
Ensure highlight is shown as a component in the local branch generated documentation.
Review code in:
* `/components/highlight/_highlight.scss`
* `/components/highlight/highlight.hbs`
* `/components/highlight/highlight.config.js`
Review content of `/components/highlight/README.md` and the description of the usage in particular.
#23 - Add highlight component
=> #23 Initial content for highlight component

README.md, components/02-form-elements/input-type/_input-type.scss, components/02-form-elements/unit/README.md, components/02-form-elements/unit/unit.config.js, components/02-form-elements/unit/unit.hbs
Adding the unit patterns from survey runner in to sdc design pattern library. Updated readme for fractal docs. 
To test:
- run yarn start on this branch
- unit should be added under 'Form Elements'
=> Eq 1307 add unit pattern to library

components/02-form-elements/currency/README.md, components/02-form-elements/currency/currency.config.js, components/02-form-elements/currency/currency.hbs
Adding the currency unit patterns from survey runner in to sdc design pattern library.
To test:
run yarn start on this branch
currency should be added under 'Form Elements'
=> Adding currency patterns from survey runner into design library

components/02-form-elements/label/label.hbs, components/02-form-elements/upload/README.md, components/02-form-elements/upload/_upload.scss, components/02-form-elements/upload/upload.config.js, components/02-form-elements/upload/upload.hbs
This is the initial work on integrating the file upload component as created for RAS mvp.
- Checkout this branch and use `yarn start` to preview the Upload component in '[Form elements](http://localhost:3000/components/detail/upload)'.
- Review `/components/02-form-elements/upload/_upload.scss`.
- Review `/components/02-form-elements/upload/upload.hbs`.
- Cross-browser test.
Resolves #35
=> Initial draft of implementing file upload input

README.md
The addition of information to document how to access the compiled resources from the Content Delivery Network (CDN).
=> Addition of information for accessing compiled resources from the CDN.

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Adds the templates used in other products for PRs and issues.
=> Add github pr and issue templates

gulpfile.babel.js
=> Hotfix - Gulp dev task fix

components/02-form-elements/date/date.config.js, components/accordion/accordion.config.js, components/guidance/guidance.config.js, components/header/header.config.js, components/timeout/timeout.config.js
=> Updated status tags for recently updated components

assets/sass/fixed.scss, assets/sass/responsive.scss, components/_preview.hbs
=> Added fixed and responsive style sheets

assets/favicons/browserconfig.xml, assets/favicons/manifest.json, components/timeout/timeout.js
=> Path and component fixes

components/02-form-elements/duration/README.md, components/02-form-elements/duration/duration.config.js, components/02-form-elements/duration/duration.hbs, components/02-form-elements/fields/field/_field.scss, components/02-form-elements/input-type/_input-type.scss, components/02-form-elements/input/_input.scss, components/02-form-elements/label/label.hbs
Pattern located under Form elements > Duration
=> Add duration as multiple input fields

components/03-grid/_grid.scss, components/_preview.hbs, components/panel/_panel.scss, components/summary/README.md, components/summary/_summary.scss, components/summary/summary--errors.hbs, components/summary/summary--group.hbs, components/summary/summary--multiple.hbs, components/summary/summary--no-edit.hbs, components/summary/summary.config.js, components/summary/summary.hbs
Updated new summary design
Check summary here: https://deploy-preview-80--sdc-global-design-patterns.netlify.com/components/detail/summary.html
And the preview here: https://deploy-preview-80--sdc-global-design-patterns.netlify.com/components/preview/summary.html
Before merging speak to @jonnyshaw89 about versioning
=> Summary accessibility amends

components/03-grid/_grid.scss
At certain widths the grid breaks in most versions of IE
Check the grid in all versions of IE
URL: https://deploy-preview-87--sdc-global-design-patterns.netlify.com/components/detail/grid--default.html
=> ie grid fix

assets/js/components.js, assets/js/polyfills.js, components/02-form-elements/mutually-exclusive/mutually-exclusive.config.js, components/02-form-elements/mutually-exclusive/mutually-exclusive.hbs, components/02-form-elements/mutually-exclusive/mutually-exclusive.js
Mutually exclusive checkboxes
Checkbox selected state should be read back in JAWS, NVDA and voiceover after deselecting all checkboxes.
=> Mutually exclusive checkboxes

components/summary/summary--errors.hbs, components/summary/summary--group.hbs, components/summary/summary--multiple.hbs, components/summary/summary--no-edit.hbs, components/summary/summary.config.js, components/summary/summary.hbs
Summary Validation across multiple pages
Check summary here: https://deploy-preview-92--sdc-global-design-patterns.netlify.com/components/preview/summary.html
=> Summary DAC amends

components/definition/definition.config.js, components/definition/definition.hbs
Added descriptive text and removed aria control
Check 'click to expand' and 'click to collapse' is read back when interacting with the link
=> Definition DAC amends

assets/img/icons/icons--chevron-breadcrumb.svg, components/breadcrumb/_breadcrumb.scss, components/breadcrumb/breadcrumb.config.js, components/breadcrumb/breadcrumb.hbs, components/breadcrumb/readme.md
- Updated the html codebase to reflect the W3 WAI guidelines for breadcrumbs.
- Updated the .scss to reflect the styling applied in ROPS/RAS
- Added detail to the README doc
Review the component in the netlify link and:
- test using VoiceOver and other assistive tech
- view the scss and check BEM naming convention is being applied correctly
=> Breadcrumb component amends

docs/01-index.md
Addition of browser support information.
Review overview page in documentation.
=> Browser support table (docs)

assets/sass/partials/base/_global.scss, assets/sass/partials/behaviours/_details-toggle.scss, assets/sass/partials/utilities/_pad.scss, assets/sass/partials/vars/_colors.scss, components/02-form-elements/fields/field/_field.scss, components/02-form-elements/input/_input.scss, components/02-form-elements/label/_label.scss, components/04-navigation/nav.js, components/04-navigation/navigation.config.json, components/04-navigation/navigation.hbs, components/04-navigation/readme.md, components/_preview__menu.hbs, components/accordion/_accordion.scss, components/button/03-button--tertiary.hbs, components/button/README.md, components/button/_buttons.scss, components/button/button--group.hbs, components/button/button--header.hbs, components/button/button--menu.hbs, components/button/button.config.js, components/definition/_definition.scss, components/definition/definition.hbs, components/panel/_panel.scss, components/panel/panel--error.hbs, components/timeout/timeout.hbs
Updated the button component and variations - accessibility, design, variants.
Updated the focus/state on all elements within the tab index.
Updated documentation on buttons. 
Check the button component area is as we want. Check the focus, state and accessibility of the button elements.
Check all other elements that have a focus state - Accordions, definitions, details, navigation, form elements.
=> Component - buttons and links

assets/sass/partials/behaviours/_details-toggle.scss, components/button/_buttons.scss, components/question/_question.scss
The latest version of PL had a couple of bugs only spotted when used by runner.
This PR fixes those bugs so we need to add this to the latest release or create new one.
Check the code.
=> Added some fixes for a couple of bugs I spotted in runner

assets/sass/partials/utilities/_pad.scss, components/summary/_summary.scss, components/summary/summary--group.hbs, components/summary/summary--multiple-textarea.hbs, components/summary/summary.config.js
Added textarea to summary
Check textarea here: https://deploy-preview-112--sdc-global-design-patterns.netlify.com/components/detail/summary.html
=> Summary textarea update

README.md, assets/sass/partials/utilities/_utilities.scss, components/button/_buttons.scss, gulpfile.babel.js
=> Script minification fix (after Node version upgrade)

assets/sass/partials/behaviours/_details-toggle.scss, components/guidance/_guidance.scss
=> Fix guidance content

components/02-form-elements/mutually-exclusive/mutually-exclusive.config.js, components/02-form-elements/mutually-exclusive/mutually-exclusive.hbs, components/02-form-elements/mutually-exclusive/readme.md
- Added detail to Notes.
- Refined the context data and template.
Review notes and suggest amendments as necessary.
=> Component mutually exclusive (notes)

assets/sass/partials/helpers/_mixins.scss, components/pagination/README.md, components/pagination/_pagination.scss, components/pagination/pagination.config.js, components/pagination/pagination.hbs
WIP of the pagination pattern for review.
Check the pagination component on the branch and review the scss.
=> Component pagination

assets/sass/partials/objects/_container.scss, assets/sass/partials/vars/_grid.scss, docs/06-grid.md
Added a modifier to the `.container` class to allow for the grid to increase to `1280px`
Check code works as expected.
=> Component grid increase

components/summary/_summary.scss, components/summary/summary--total.hbs, components/summary/summary.config.js
=> Summary total with variants

README.md, docs/01-index.config.js, docs/01-index.md, docs/08-feedback.md
- Updating the code standards write up on the overview page
- Housekeeping on feedback and root readme
Review the content and suggest amendments as you see fit.
=> Documentation on code standards

components/header/_header.scss
Fixes the issue described here:
https://github.com/ONSdigital/eq-survey-runner/issues/1103
Check rendering in FF
=> Fixed issue with text rendering in Firefox for the header component

components/timeout/timeout.hbs
Added utility class to the continue button to provide `1rem` of spacing.
Check the timeout component button spacing on the netlify instance.
Resolves #151
=> Timeout button spacing fix

components/status/README.md, components/status/_status.scss, components/status/status.config.js, components/status/status.hbs
Initial build of the status component
Review the code and the status component on the Netlify instance.
=> Component status

assets/js/form-submitter.js, components/collapsible/_collapsible.scss, components/feedback/feedback.hbs, components/icons/_icons.scss
Fixed issue with form submitter js. The form data wasn't being read and added to the POST.
Fixed a line height issue with the `collapsible--simple` title
=> Fixed issue with no data being added to the form submit

README.md
* added relevant badges for release version and github statuses
* amended CDN information to make it more usable.
Review base readme.md
=> Addition of badges

components/footer/_footer.scss, components/footer/footer--poweredbyons-transactional-cy.hbs, components/footer/footer--poweredbyons-transactional.hbs, components/footer/footer--poweredbyons.hbs
Amended the powered by logo to match size of the ONS logo in the standard header.
Review on Netlify instance for this PR.
Closes #169
=> Amended powered by logo size and OGL logo to match

assets/sass/partials/vars/_colors.scss
Amended the highlight variable to the yellow tint agreed upon in a previous design team meeting.
- Check the colour value matches the intended.
- Check the contrast ratio
- Check the highlight component.
=> Highlight colour to use the new yellow tint

README.md
Correcting the fractal version badge to v1.1.7 from v1.7.1
Check root readme docs
=> Correcting fractal version number

assets/img/icons/icons--check-green.svg, components/04-navigation/_nav.scss
Replaces existing blue tick with new tick icon and updates .scss to use icon mixin.
x-broswer test the vertical section nav and review the .scss.
https://deploy-preview-195--sdc-global-design-patterns.netlify.com/components/detail/vertical-navigation.html
Closes #194
=> Issue 194 fix - new tick icon

assets/js/polyfills.js, package.json, yarn.lock
Add Array#find and Array#from polyfills to resolve IE errors on runner.
=> Add array polyfills

components/language/language.config.js, components/language/language.hbs, components/language/readme.md
Added a language toggle component with example GA attributes.
This component will also be used to document a solution for selection of a language from > 2 languages.
Review code and 'Language selection' component.
Closes: #208
=> Language: addition of language selection component

components/02-form-elements/mutually-exclusive/mutually-exclusive.js
=> Changed event type in js to deal with safari bug

.gitignore, package.json
Added `--force` to yarn install step.
=> Ensure yarn installs fresh dependencies for every build

components/address/README.md, components/address/address.config.js
=> Add deprecated status to address and add read me

docs/01-index.md
Removed older browsers which do not require continued support.
Review docs output and ensure table matches that of GDS as referred to.
=> Updated browser compatibility chart to match GDS.

components/collapsible/collapsible.js, tests/karma/spec/accordion.spec.js
Each instance of the collapsible component (accordion etc) would create the same id pattern for the title and body. 
This meant duplicate id's.
Each instance has a unique id for the titles and body elements
=> Apply unique id to each element

components/collapsible/collapsible.js
=> Fix issue with toggle all panels

components/02-form-elements/mutually-exclusive/mutually-exclusive.js, tests/karma/spec/mutuallyexclusive.spec.js
Resolves https://github.com/ONSdigital/sdc-global-design-patterns/issues/233
Check mutually exclusive still works correctly and that unit tests are acceptable.
=> Ensure mutually exclusive works with input types other than text

assets/img/icons/icons--chevron-down.svg
=> Select caret does not show in IE11
